{% set name = "opentracing" %}
{% set version = "2.0.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "39a999847b1827112ca6ccdb1c66e315c6a5ecd53131eed1ae363223671a9d68" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_value }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - futures  # [py2k]

test:
  imports:
    - opentracing

about:
  home: http://opentracing.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: OpenTracing API for Python.
  description: |
    opentracing-python provides only the API and a basic no-op implementation
    that can be used by instrumentation libraries to collect and propagate
    distributed tracing context
  doc_url: http://opentracing.io/documentation
  dev_url: https://github.com/opentracing/opentracing-python

extra:
  recipe-maintainers:
    - nehaljwani
