appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: nIOf1WufO612IYCcRepFvBnTe9xsj29T0tFtsr3BkI95gS8cgu9URkO941jgAB1j8R/jGzWRVqec0LyZqrexlBgWW+hVPhWeR7a4ncHE7awRJcDWyQd8F85k1MaQnSoKrfEAELfcltwc8W2E+e6isW1+ZTaEt+NV2cYc04Q7CmhOrhpYmyJeOKUS3F39GeMXQf3sUUi4iqpbiQTWFRveuIPvjCfwAsGTQvwIubPU+HszD9zn040rMcVv82WP7HajV8IQF/LfvIe9k3RudWEr3UhiRhlAKg0lzF13DapqG3WGBkhlt3t4E4J7uOM+UCrqgxlDCopZfoxlOUjnoVgN2/gQYMTbyEGY97RVruhuqk0ueUcRE3/Pe4hK0pX/zNRdOzOr0Dj+CclDvC5NMyd7wy93AFfPfrMsrarIsMGp4bbjTjK784j+uFCj/vzd1Zv1jjx26UrHF4E9rcY5sN5wxY7YS6oGbhvVfJDevQOUCSre1NkEqc0vaoMH6pj6LaI5D4h/RKUpzGZdcY57aP4FD56qNMcGeLezQucOgE5/MTQes64n11074CPIjAOLpvDRdy9JfJizXQ2OdIOPQMn8+bh3/07R+qqsXVuDFLkDTq3zIAyyu/d+Ok2GxkAcz+bqJk5UtFoHfIRoNeonwQvhZZcg3056Me0s4TNuOgATOfw=}
